### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by jskew** [harlamism/IdaClu#2]
idaclu\ida_utils.py

while func_name[idx+pfx_len] == '_':
IndexError: string index out of range

func_name = 'dynamic_initializer_for__CDeviceEventHandler::s_saDOCD__'

while func_name[idx+pfx_len] == '_':
while (idx+pfx_len) < len(func_name) and func_name[idx+pfx_len] == '_':

**Comment by zhefox** [comment]
I am the same as you.

IDAPython: Error while calling Python callback <OnCreate>:
Traceback (most recent call last):
  File "C:/Users/xxx/Desktop/IDA/IDA7.7/plugins/idaclu.py", line 203, in OnCreate
    self.dialog = idaclu_gui.IdaCluDialog(self.env_desc)
  File "C:\Users\xxx\Desktop\IDA\IDA7.7\plugins\idaclu\idaclu_gui.py", line 97, in __init__
    self.initPrefixFilter()
  File "C:\Users\xxx\Desktop\IDA\IDA7.7\plugins\idaclu\idaclu_gui.py", line 138, in initPrefixFilter
    prefixes = self.getFuncPrefs(is_dummy=True)
  File "C:\Users\xxx\Desktop\IDA\IDA7.7\plugins\idaclu\idaclu_gui.py", line 128, in getFuncPrefs
    func_prefs = ida_utils.get_func_prefs(func_name, is_dummy)
  File "C:\Users\xxx\Desktop\IDA\IDA7.7\plugins\idaclu\ida_utils.py", line 75, in get_func_prefs
    while func_name[idx+pfx_len] == '_':
IndexError: string index out of range
